# Generated by Django 2.1.2 on 2018-11-28 21:56

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('nota', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='friendship',
            unique_together={('friend1', 'friend2')},
        ),
        migrations.AlterUniqueTogether(
            name='shared',
            unique_together={('shared_to', 'note')},
        ),
    ]
